cookbook/bookapp/urls.py
from django.urls import path
from bookapp import views


app_name = 'bookapp'

urlpatterns = [
    path('', views.MainView.as_view(), name='index'),
    path('create/', views.RecipeCreateView.as_view(), name='create'),
    path('contact/', views.contact, name='contact'),
    path('post/<int:id>/', views.post, name='post'),
    path('recipe-detail/<int:pk>/', views.RecipeDetailView.as_view(), name='recipe_detail'),
    path('ingredient-list', views.IngredientListView.as_view(), name='ingredient_list'),
    path('ingredient-detail/<int:pk>/', views.IngredientDetailView.as_view(), name='ingredient_detail'),
    path('ingredient-create/', views.IngredientCreateView.as_view(), name='ingredient_create'),
    path('ingredient-update/<int:pk>/', views.IngredientUpdateView.as_view(), name='ingredient_update'),
    path('ingredient-delete/<int:pk>/', views.IngredientDeleteView.as_view(), name='ingredient_delete'),
    path('ingredient-list/<int:pk>/', views.IngredientFilterListView.as_view(), name='ingredient_list'),
    path('ingredient-group', views.GroupListView.as_view(), name='ingredient_group'),
    path('recipe-update/<int:pk>/', views.RecipeUpdateView.as_view(), name='recipe_update'),
    # path('recipe-update/<int:pk>/', views.RecipeUpdateViewPlus.as_view(), name='recipe_update'),
    path('recipe-delete/<int:pk>/', views.RecipeDeleteView.as_view(), name='recipe_delete'),
    path('category-detail/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('category-list', views.CategoryListView.as_view(), name='category_list'),
    path('category-create/<int:pk>/', views.RecipeCategoryCreateView.as_view(), name='recipe_category_create'),
    path('category-update/<int:pk>/', views.RecipeCategoryCreateView.as_view(), name='category_update'),
    path('sostav-update/<int:pk>/', views.SostavUpdateView.as_view(), name='sostav_update'),
    path('manage-sostav/<int:id>/', views.managesostav, name='manage_sostav'),

    path('sostav-recipe/<int:id>/', views.alsorecipe, name='sostav_recipe'),
    path('simple/', views.SimpleMainAjax.as_view(), name='simple_ajax'),
]

cookbook/cookbook/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from bookapp.api_views import CategoryViewSet, RecipeViewSet, DifficultyViewSet, Ingredients_groupViewSet, \
    IngredientViewSet, MeasureUnitViewSet, Ingredient_RecipeViewSet, Recipe1ViewSet
# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'recipebot', Recipe1ViewSet)
router.register(r'recipe', RecipeViewSet)
router.register(r'difficulty', DifficultyViewSet)
router.register(r'ingredients_group', Ingredients_groupViewSet)
router.register(r'ingredient', IngredientViewSet)
router.register(r'measureunit', MeasureUnitViewSet)
router.register(r'ingredientrecipe', Ingredient_RecipeViewSet)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookapp.urls', namespace='cookbook')),
    path('users/', include('userapp.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    # path('api/v0/categories/', include(router.urls)),
    # path('api/v0/posts/', include(router_p.urls)),
    path('api/v0/', include(router.urls)),
]



if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),


    ] + urlpatterns

cookbook/userapp/urls.py
from django.urls import path
from userapp import views
from django.contrib.auth.views import LogoutView

app_name = 'userapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('profile-list', views.ProfileListView.as_view(), name='profile_list'),
    path('profile-detail/<int:pk>/', views.ProfileDetailView.as_view(), name='profile_detail'),
    path('profile-create/', views.ProfileCreateView.as_view(), name='profile_create'),
    path('profile-update/<int:pk>/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('profile-delete/<int:pk>/', views.ProfileDeleteView.as_view(), name='profile_delete'),
    path('update-token/', views.update_token, name='update_token'),
    path('update-token-ajax/', views.update_token_ajax),
]

cookbook/userapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class BookUser(AbstractUser):
    email = models.EmailField(unique=True)
    is_author = models.BooleanField(default=False)
    # profile = models.ForeignKey(Profile, blank=True, related_name='profile')

    # Переопределение метода save
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # Создаем профиль
        # Если профиль не создан
        if not Profile.objects.filter(user=self).exists():
            Profile.objects.create(user=self)

class Profile(models.Model):
    # При создании пользователя создать Profile
    info = models.TextField(blank=True)
    user = models.OneToOneField(BookUser, on_delete=models.CASCADE)



# @receiver(post_save, sender=BlogUser)
# def create_profile(sender, instance, **kwargs):
#     print('Сработал обработчик сигнала')
#     if not Profile.objects.filter(user=instance).exists():
#         Profile.objects.create(user=instance)

cookbook/userapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import BookUser


class RegistrationForm(UserCreationForm):
    class Meta:
        model = BookUser
        fields = ('username', 'password1', 'password2', 'email')

cookbook/userapp/views.py
from django.http import JsonResponse
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy, reverse

from bookapp.context_processors import get_profile
from .forms import RegistrationForm

from .models import BookUser, Profile
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from rest_framework.authtoken.models import Token

# Create your views here.
class UserLoginView(LoginView):
    template_name = 'userapp/login.html'


class UserCreateView(CreateView):
    model = BookUser
    template_name = 'userapp/register.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('users:login')


class ProfileListView(ListView):
    model = Profile
    template_name = 'userapp/profile_list.html'
    paginate_by = 10



# детальная информация
class ProfileDetailView(DetailView):
    fields = '__all__'
    model = Profile
    template_name = 'userapp/profile_detail.html'

    def get(self, request, *args, **kwargs):
        """
        Метод обработки get запроса
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        self.id = kwargs['pk']
        return super().get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        """
        Получение этого объекта
        :param queryset:
        :return:
        """
        return get_object_or_404(Profile, pk=self.id)


# создание тега
class ProfileCreateView(LoginRequiredMixin, CreateView):
    # form_class =
    fields = '__all__'
    model = Profile
    success_url = reverse_lazy('users:login')
    template_name = 'userapp/profile_create.html'

    def post(self, request, *args, **kwargs):
        """
        Пришел пост запрос
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        """
        Метод срабатывает после того как форма валидна
        :param form:
        :return:
        """
        return super().form_valid(form)


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    fields = '__all__'
    model = Profile
    success_url = reverse_lazy('users:login')
    template_name = 'userapp/profile_create.html'


class ProfileDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'userapp/profile_delete.html'
    model = Profile
    success_url = reverse_lazy('users:login')


def update_token(request):
    user = request.user
    profile_id = get_profile(request)
    print(user)
    # если уже есть

    if user.auth_token:
        # обновить
        user.auth_token.delete()
        Token.objects.create(user=user)
    else:
        # создать
        Token.objects.create(user=user)

    return HttpResponseRedirect(reverse('users:profile_detail', kwargs={'pk': profile_id['profile_id']}))

def update_token_ajax(request):
    user = request.user
    # если уже есть
    if user.auth_token:
        # обновить
        user.auth_token.delete()
        token = Token.objects.create(user=user)
    else:
        # создать
        token = Token.objects.create(user=user)
    return JsonResponse({'key': token.key})

cookbook/userapp/templates/userapp/login.html
{% extends "base.html" %}

{% block title %}
Вход
{% endblock %}

{% block content %}
  <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Войти</button>
    </form>
{% endblock %}

cookbook/userapp/templates/userapp/profile_create.html
{% extends "base.html" %}

{% block title %}
Редактирование профиля
{% endblock %}

{% block content %}
<div class="row">
    <h1>{{name}}</h1>
    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}

cookbook/userapp/templates/userapp/profile_delete.html
{% extends "base.html" %}

{% block title %}
{{object.name}}
{% endblock%}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        {{object.name}}
    </div>

    Вы уверены?
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Да</button>
    </form>
</div>
{% endblock %}

cookbook/userapp/templates/userapp/profile_detail.html
{% extends "base.html" %}

{% block title %}
{{post.name}}
{% endblock%}

{% block content %}
<div class="row">
    <h1>{{name}}</h1>
    <div class="col-lg-8 col-md-10 mx-auto">
        {{object.user.username}} ---
        {{object.info}}

          Токен:
<span id="token">{% if object.user.auth_token %} {{object.user.auth_token}} {% else %} не создан {% endif %}</span>

<form action="{% url 'users:update_token' %}">
        <button type="submit" class="btn btn-primary">Новый токен</button>

    </form>
        <button type="button" id="ajax-btn" class="btn btn-info">Refresh token ajax</button>


        </div>
    <a href="{% url 'users:profile_update' pk=object.pk %}">
            Изменить
        </a>
</div>
{% endblock %}

cookbook/userapp/templates/userapp/profile_list.html
{% extends "base.html" %}

{% block title %}
Список пользователей
{% endblock %}

{% block content %}
<h1>{{name}}</h1>


<ul>
    {% for item in object_list %}
    <li>
        <a href="{% url 'users:profile_detail' pk=item.pk %}">
           {{item.user.username}} --- {{item.user.email}} --- {{item.info}}
        </a>
<br>
        <a href="{% url 'users:profile_update' pk=item.pk %}">
            Изменить
        </a>
        |

        <a href="{% url 'users:profile_delete' pk=item.pk %}">
            Удалить
        </a>

    </li>
    {% endfor %}

   {# <a href="{% url 'users:profile_create' %}">Создать</a> #}
</ul>

<!-- Pager -->

        <div class="clearfix">
            <div class="pagination">

            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
{#               <a href="?page={{ page_obj.next_page_number }}">next</a> #}


                    <a class="btn btn-primary float-right"
                       href="?page={{ page_obj.next_page_number }}">Older Posts &rarr;</a>

                {% endif %}


            </span>
            </div>
        </div>
{% endblock %}

cookbook/userapp/templates/userapp/register.html
{% extends "base.html" %}

{% block title %}
Регистрация
{% endblock %}

{% block content %}
  <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Зарегистрироваться</button>
    </form>
{% endblock %}