cookbook/bookapp/urls.py
from django.urls import path
from bookapp import views


app_name = 'bookapp'

urlpatterns = [
    path('', views.MainView.as_view(), name='index'),
    path('create/', views.RecipeCreateView.as_view(), name='create'),
    path('contact/', views.contact, name='contact'),
    path('post/<int:id>/', views.post, name='post'),
    path('recipe-detail/<int:pk>/', views.RecipeDetailView.as_view(), name='recipe_detail'),
    path('ingredient-list', views.IngredientListView.as_view(), name='ingredient_list'),
    path('ingredient-detail/<int:pk>/', views.IngredientDetailView.as_view(), name='ingredient_detail'),
    path('ingredient-create/', views.IngredientCreateView.as_view(), name='ingredient_create'),
    path('ingredient-update/<int:pk>/', views.IngredientUpdateView.as_view(), name='ingredient_update'),
    path('ingredient-delete/<int:pk>/', views.IngredientDeleteView.as_view(), name='ingredient_delete'),
    path('ingredient-list/<int:pk>/', views.IngredientFilterListView.as_view(), name='ingredient_list'),
    path('ingredient-group', views.GroupListView.as_view(), name='ingredient_group'),
    path('recipe-update/<int:pk>/', views.RecipeUpdateView.as_view(), name='recipe_update'),
    # path('recipe-update/<int:pk>/', views.RecipeUpdateViewPlus.as_view(), name='recipe_update'),
    path('recipe-delete/<int:pk>/', views.RecipeDeleteView.as_view(), name='recipe_delete'),
    path('category-detail/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('category-list', views.CategoryListView.as_view(), name='category_list'),
    path('category-create/<int:pk>/', views.RecipeCategoryCreateView.as_view(), name='recipe_category_create'),
    path('category-update/<int:pk>/', views.RecipeCategoryCreateView.as_view(), name='category_update'),
    path('sostav-update/<int:pk>/', views.SostavUpdateView.as_view(), name='sostav_update'),
    path('manage-sostav/<int:id>/', views.managesostav, name='manage_sostav'),

    path('sostav-recipe/<int:id>/', views.alsorecipe, name='sostav_recipe'),
    path('simple/', views.SimpleMainAjax.as_view(), name='simple_ajax'),
]

cookbook/cookbook/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from bookapp.api_views import CategoryViewSet, RecipeViewSet, DifficultyViewSet, Ingredients_groupViewSet, \
    IngredientViewSet, MeasureUnitViewSet, Ingredient_RecipeViewSet, Recipe1ViewSet
# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'recipebot', Recipe1ViewSet)
router.register(r'recipe', RecipeViewSet)
router.register(r'difficulty', DifficultyViewSet)
router.register(r'ingredients_group', Ingredients_groupViewSet)
router.register(r'ingredient', IngredientViewSet)
router.register(r'measureunit', MeasureUnitViewSet)
router.register(r'ingredientrecipe', Ingredient_RecipeViewSet)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookapp.urls', namespace='cookbook')),
    path('users/', include('userapp.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    # path('api/v0/categories/', include(router.urls)),
    # path('api/v0/posts/', include(router_p.urls)),
    path('api/v0/', include(router.urls)),
]



if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),


    ] + urlpatterns

cookbook/bookapp/forms.py
from django import forms
from .models import Recipes
from .models import Ingredient, Ingredient_Recipe
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView



class ContactForm(forms.Form):
    name = forms.CharField(label='Название')
    email = forms.EmailField(label='email')
    message = forms.CharField(label='Сообщение')


class PostForm(forms.ModelForm):
    # name = forms.CharField(label='Название',
    #                        widget=forms.TextInput(attrs={'placeholder': 'Название', 'class': 'form-control'}))
    # description = forms.CharField(label='Описание',
    #                               widget=forms.Textarea(attrs={'placeholder': 'Описание', 'class': 'form-control'}))
    # duration = forms.DurationField(label='Время приготовления',widget=forms.TextInput(attrs={'placeholder': 'Название', 'class': 'form-control'}))
    # portions = forms.CharField(label="Количество порций", widget=forms.NumberInput())
    # text = forms.CharField(label='Технология приготовления',
    #                               widget=forms.Textarea(attrs={'placeholder': 'Технология приготовления', 'class': 'form-control'}))
    # # picture = models.ImageField(upload_to='posts', null=True, blank=True)
    # ingredients = models.ManyToManyField(Ingredient, through='Ingredient_Recipe', blank=True)
    # category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_recipe', db_index=True)
    # difficulty = models.ForeignKey(Difficulty, on_delete=models.CASCADE)
    # duration = models.TimeField()
    # portions = models.PositiveSmallIntegerField()
    # text = models.TextField()
    # # Чекбоксы
    # ingredients = forms.ModelMultipleChoiceField(queryset=Ingredient.objects.all(),
    #                                       widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Recipes
        # fields = '__all__'
        # fields = ('name', 'category')
        exclude = ('ingredients', 'author', 'is_active')



class RecipeCategoryForm(forms.ModelForm):
    name = forms.CharField(label='Название',
                           widget=forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}))

    # # Чекбоксы
    # ingredients = forms.ModelMultipleChoiceField(queryset=Ingredient.objects.all(),
    #                                       widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Recipes
        # fields = '__all__'
        # fields = ('name', 'category')
        exclude = ('category', 'ingredients', 'author', 'is_active')


class SostavUpdateForm(forms.ModelForm):
    name = forms.CharField(label='Название',
                           widget=forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}))



    class Meta:
        model = Ingredient_Recipe
        # fields = '__all__'
        # fields = ('name', 'category')
        exclude = ('recipe',)

class RecipeUpdateForm(forms.ModelForm):
    name = forms.CharField(label='Название',
                           widget=forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}))
    description = forms.CharField(label='Описание',
                                  widget=forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}))

    # picture = models.ImageField(upload_to='posts', null=True, blank=True)
    # ingredients = models.ManyToManyField(Ingredient, through='Ingredient_Recipe', blank=True)
    # category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_recipe', db_index=True)
    # difficulty = models.ForeignKey(Difficulty, on_delete=models.CASCADE)
    # duration = models.TimeField()
    # portions = models.PositiveSmallIntegerField()
    # text = models.TextField()
    # # Чекбоксы
    # ingredients = forms.ModelMultipleChoiceField(queryset=Ingredient.objects.all(),
    #                                       widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Recipes
        # fields = '__all__'
        # fields = ('name', 'category')
        exclude = ('ingredients', 'author', 'is_active')

cookbook/bookapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .models import Ingredient
from .models import Recipes, Category, Ingredients_group, Ingredient_Recipe
from .forms import ContactForm, PostForm, RecipeCategoryForm, SostavUpdateForm, RecipeUpdateForm
from django.core.mail import send_mail
from django.views.generic.base import ContextMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView,  TemplateView
from django import forms
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.forms import formset_factory, modelformset_factory, inlineformset_factory

# Create your views here.
# def main_view(request):
#     posts = Recipes.objects.all()
#     return render(request, 'bookapp/index.html', context={'posts': posts})


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # Получить данные из формы
            name = form.cleaned_data['name']
            message = form.cleaned_data['message']
            email = form.cleaned_data['email']

            send_mail(
                'Contact message',
                f'Ваш сообщение {message} принято',
                'from@example.com',
                [email],
                fail_silently=True,
            )

            return HttpResponseRedirect(reverse('cookbook:index'))
        else:
            return render(request, 'bookapp/contact.html', context={'form': form})
    else:
        form = ContactForm()
        return render(request, 'bookapp/contact.html', context={'form': form})

def post(request, id):
    post = get_object_or_404(Recipes, id=id)
    return render(request, 'bookapp/post.html', context={'post': post})

@login_required
def create_recipe(request):
    if request.method == 'GET':
        form = PostForm()
        return render(request, 'bookapp/create.html', context={'form': form})
    else:
        form = PostForm(request.POST, files=request.FILES)
        if form.is_valid():
            form.instance.author = request.user
            form.save()
            return HttpResponseRedirect(reverse('cookbook:index'))
        else:
            return render(request, 'bookapp/create.html', context={'form': form})

class NameContextMixin(ContextMixin):

    def get_context_data(self, *args, **kwargs):
        """
        Отвечает за передачу параметров в контекст
        :param args:
        :param kwargs:
        :return:
        """
        context = super().get_context_data(*args, **kwargs)
        context['name'] = 'Продукты:'
        return context
# CRUD CREATE, READ (LIST, DETAIL), UPDATE, DELETE
# список тегов
class IngredientListView(ListView, NameContextMixin):
    model = Ingredient
    template_name = 'bookapp/ingredient_list.html'
    paginate_by = 20
    context_object_name = 'Ingredient'
    def get_queryset(self):

        return Ingredient.objects.select_related('group').order_by('name')


class IngredientFilterListView(ListView, NameContextMixin):
    model = Ingredient
    template_name = 'bookapp/ingredient_list.html'
    context_object_name = 'Ingredient'
    paginate_by = 20
    def get_queryset(self):

        self.group = get_object_or_404(Ingredients_group, id=self.kwargs['pk'])
        return Ingredient.objects.select_related('group').filter(group=self.group)




# детальная информация
class IngredientDetailView(DetailView, NameContextMixin):

    fields = '__all__'
    model = Ingredient
    template_name = 'bookapp/ingredient_detail.html'

    def get(self, request, *args, **kwargs):
        """
        Метод обработки get запроса
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        self.tag_id = kwargs['pk']
        return super().get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        """
        Получение этого объекта
        :param queryset:
        :return:
        """
        return get_object_or_404(Ingredient, pk=self.tag_id)


# создание тега
class IngredientCreateView(LoginRequiredMixin, CreateView, NameContextMixin):
    # form_class =
    fields = '__all__'
    model = Ingredient
    success_url = reverse_lazy('cookbook:ingredient_list')
    template_name = 'bookapp/ingredient_create.html'

    def post(self, request, *args, **kwargs):
        """
        Пришел пост запрос
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        """
        Метод срабатывает после того как форма валидна
        :param form:
        :return:
        """
        return super().form_valid(form)


class IngredientUpdateView(LoginRequiredMixin,UpdateView):
    fields = '__all__'
    model = Ingredient
    success_url = reverse_lazy('cookbook:ingredient_list')
    template_name = 'bookapp/ingredient_create.html'


class IngredientDeleteView(UserPassesTestMixin,LoginRequiredMixin,DeleteView):
    template_name = 'bookapp/ingredient_delete.html'
    model = Ingredient
    success_url = reverse_lazy('cookbook:ingredient_list')

    def test_func(self):
        return self.request.user.is_superuser

class GroupListView(ListView, NameContextMixin):
    model = Ingredients_group
    template_name = 'bookapp/ingredient_group.html'
    context_object_name = 'Group'

    # def get_queryset(self):
    #     """
    #     Получение данных
    #     :return:
    #     """
    #     return Ingredient.objects.filter()


class MainView(ListView):
    model = Recipes
    title = 'вкуСняшки от Машки'
    template_name = 'bookapp/main.html'
    paginate_by = 20
    context_object_name = 'Recipes'

    # class Meta:
    #     ordering = ['-id']


    def get_queryset(self):
        return Recipes.active_objects.select_related('category', 'author').order_by('name').all()



class RecipeCreateView(LoginRequiredMixin, CreateView):
    # form_class =
    model = Recipes
    # fields = '__all__'
    # fields = ('picture',
    #           'category',
    #           'difficulty',
    #           'duration',
    #           'portions',
    #           'text')
    form_class = PostForm

    template_name = 'bookapp/recipe_create.html'
    def form_valid(self, form):
        """
        Метод срабатывает после того как форма валидна
        :param form:
        :return:
        """
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        #return reverse('bookapp:sostav_update')
        return reverse('bookapp:sostav_recipe', kwargs={'id': self.object.id} )



class RecipeDetailView(DetailView):
    fields = '__all__'

    model = Recipes
    # ingredient = forms.ModelMultipleChoiceField(queryset=Ingredient.objects.all(),
    #                                       widget=forms.CheckboxSelectMultiple())
    template_name = 'bookapp/recipe_detail.html'

    # def get_context_data(self, **kwargs):
    #     context = super(RecipeDetailView, self).get_context_data(**kwargs)
    #     context['sostav'] = Ingredient_Recipe.objects.filter(
    #         recipe=self.object)
    #     print(context)
    #     return context

    def get(self, request, *args, **kwargs):
        """
        Метод обработки get запроса
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        self.tag_id = kwargs['pk']
        return super().get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        """
        Получение этого объекта
        :param queryset:
        :return:
        """
        return get_object_or_404(Recipes, pk=self.tag_id)

class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    fields = ('name',
        'picture',
    'category' ,
    'difficulty',
    'duration',
    'portions',
    'text')

    model = Recipes

    template_name = 'bookapp/recipe_create.html'
    def form_valid(self, form):
        """
        Метод срабатывает после того как форма валидна
        :param form:
        :return:
        """
        form.instance.author = self.request.user
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        self.pk = kwargs['pk']
        return super().post(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        """
        Метод обработки get запроса
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        self.r_id = kwargs['pk']
        return super().get(request, *args, **kwargs)



    def get_success_url(self):
        #return reverse('bookapp:sostav_update', kwargs={'pk': self.id})
        return reverse('bookapp:sostav_recipe', kwargs={'id': self.pk})

class RecipeDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'bookapp/ingredient_delete.html'
    model = Recipes
    success_url = reverse_lazy('cookbook:index')

    def test_func(self):
        return self.request.user.is_superuser


class CategoryDetailView(DetailView):
    template_name = 'bookapp/category_detail.html'
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = RecipeCategoryForm()
        return context

class CategoryListView(ListView):
    model = Category
    template_name = 'bookapp/category_list.html'
    paginate_by = 20


class RecipeCategoryCreateView(CreateView):
    model = Recipes
    template_name = 'bookapp/category_detail.html'
    success_url = reverse_lazy('')
    form_class = RecipeCategoryForm

    def post(self, request, *args, **kwargs):
        self.category_pk = kwargs['pk']
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        user = self.request.user

cookbook/bookapp/templates/bookapp/category_detail.html
{% extends "base.html" %}

{% block title %}
{{post.name}}
{% endblock%}

{% block content %}
<div class="row">

    <div class="col-lg-8 col-md-10 mx-auto">
        {{object.name}}
    </div>

 {% for recipe in object.category_recipe.all %}
 <a href="{% url 'cookbook:recipe_detail' pk=recipe.pk %}">

                 <h5>
                   {{ recipe.name }}
                </h5>
        <hr>
        {% endfor %}

  {#      <form method="post" action="{% url 'bookapp:recipe_category_create' pk=object.pk %}">  #}
   {#           {% csrf_token %}  #}
   {#           {{form.as_p}} #}
   {#           <button type="submit">Сохранить</button> #}
   {#       </form> #}

</div>
{% endblock %}

cookbook/bookapp/templates/bookapp/contact.html
{% extends "base.html" %}

{% block title %}
Создание письма
{% endblock %}

{% block content %}
Имя бота: <br>
@masia_1_bot

<hr>
Доступные команды:  <br>
<li> /timer - Таймер на 10 секунд <li>/help - помощь<li>/list - список категорий
    <li>/rnd - случайный рецепт
<li>/echo - эхо<li>/rev - перевернутое эхо
<hr>
    Планируемые команды:  <br>
<li> поиск по категории
<li> поиск по ингредиентам
<li> фильтр в найденном по сложности
{% endblock %}

cookbook/bookapp/templates/bookapp/create.html
{% extends "base.html" %}

{% block title %}
Создание рецепта
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {# form.as_ul #}
            {% for field in form %}
            <p>{{field.label_tag}}</p>
            <hr>
            {% for error in field.errors %}
            {{error}}
            {% endfor %}
            <p>{{field}}</p>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}

cookbook/bookapp/templates/bookapp/index.html
{% extends "base.html" %}

{% block title %}
Главная
{% endblock %}

{% block content %}
<div class="row">
    Количество постов на странице: {{posts|length}}
    <div class="col-lg-8 col-md-10 mx-auto">
        {% for item in posts %}
        <div class="post-preview">
            <a href="{% url 'cookbook:post' id=item.id %}">
                <h2 class="post-title">
                    {{ item.name }}
                </h2>
                <h3 class="post-subtitle">
                    Описание ({{item.category.name}}) ({{item.user.username}})
                </h3>
            </a>
            <p class="post-meta">Posted by
                <a href="#">Start Bootstrap</a>
                on September 24, 2019.
                {% if item.has_image %}
                Есть картинка
                {% else%}
                Нет картинки
                {% endif %}
                {{item.has_image}}
                {{item.some_method}}
            </p>
        </div>
        <hr>
        {% endfor %}
        <!-- Pager -->

        <div class="clearfix">
            <div class="pagination">

            <span class="step-links">
                {% if posts.has_previous %}
                    <a href="?page={{ posts.previous_page_number }}">Предыдущая</a>
                {% endif %}

                <span class="current">
                    Страница {{ posts.number }} из {{ posts.paginator.num_pages }}.
                </span>

                {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">Следующая</a>




                {% endif %}


            </span>
            </div>
        </div>

    </div>
</div>
{% endblock %}

cookbook/bookapp/templates/bookapp/ingredient_create.html
{% extends "base.html" %}

{% block title %}
Добавление ингредиента
{% endblock %}

{% block content %}
<div class="row">
    <h1>{{name}}</h1>
    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-secondary">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}

cookbook/bookapp/templates/bookapp/ingredient_delete.html
{% extends "base.html" %}

{% block title %}
{{object.name}}
{% endblock%}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        {{object.name}}
    </div>

    Вы уверены?
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Да</button>
    </form>
</div>
{% endblock %}

cookbook/bookapp/templates/bookapp/ingredient_detail.html
{% extends "base.html" %}

{% block title %}
{{post.name}}
{% endblock%}

{% block content %}
<div class="row">
    <h1>{{name}}</h1>
    <div class="col-lg-8 col-md-10 mx-auto">
      <h4>{{object.name}}</h4>   <br>
         {{object.description}} <br>
        Группа {{object.group}}
    </div>

    <a href="{% url 'cookbook:ingredient_update' pk=object.pk %}">
            Изменить
        </a>
</div>
{% endblock %}

cookbook/bookapp/templates/bookapp/ingredient_group.html
{% extends "base.html" %}

{% block title %}
Группы продуктов
{% endblock %}

{% block content %}
<h1>{{name}}</h1>
<ul>
    {% for item in Group %}
    <li>
     <h5>   <a href="{% url 'cookbook:ingredient_list' pk=item.pk %}">
            {{item.name}}
        </a>
</h5>

    </li>
    {% endfor %}

</ul>
{% endblock %}

cookbook/bookapp/templates/bookapp/main.html
{% extends "base.html" %}

{% block title %}
Главная
{% endblock %}

{% block content %}
<h1>{{name}}</h1>
Количество постов на странице: {{Recipes|length}}

<ul>
    {% for item in Recipes %}
    <li>
        <a href="{% url 'cookbook:recipe_detail' pk=item.pk %}">
         <h5>  {{item.name}} ({{item.category.name}})</h5>
            {% if item.has_image %}
             <img src="{{item.picture.url}}", width="60">
            {% endif %}
        </a>
<br>                   <a href="{% url 'cookbook:recipe_update' pk=item.pk %}">
            Изменить
        </a>
        |

        <a href="{% url 'cookbook:recipe_delete' pk=item.pk %}">
            Удалить
        </a>

    </li>
    {% endfor %}
<hr>
    <a href="{% url 'cookbook:create' %}">Создать новый рецепт</a>
</ul>

 <!-- Pager -->

        <div class="clearfix">
            <div class="pagination">

            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">Назад</a>

                {% endif %}

                <span class="current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
             <a href="?page={{ page_obj.next_page_number }}">Далее</a>




                {% endif %}


            </span>
            </div>
        </div>
{% endblock %}

cookbook/bookapp/templates/bookapp/recipe_category_create.html
{% extends "base.html" %}

{% block title %}
Добавление ингредиента
{% endblock %}

{% block content %}
<div class="row">
    <h1>{{name}}</h1>
    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}

cookbook/bookapp/templates/bookapp/recipe_create.html
{% extends "base.html" %}

{% block title %}
Новый рецепт
{% endblock %}

{% block content %}
<div class="row">
    <h1>{{name}}</h1>

    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-secondary">Далее</button>
        </form>
    </div>
</div>
{% endblock %}

cookbook/bookapp/templates/bookapp/recipe_create1.html
{% extends "base.html" %}

{% block title %}
Редактор рецепта
{% endblock %}

{% block content %}
<div class="row">
    <h1>{{name}}</h1>

    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
             {{ details_form.as_p }}
            {{ form.as_p }}



            <button type="submit" class="btn btn-primary">OK</button>
        </form>
    </div>
</div>
{% endblock %}

cookbook/bookapp/templates/bookapp/recipe_detail.html
{% extends "base.html" %}

{% block title %}
{{object.name}}
{% endblock%}

{% block content %}

    <h1>{{object.name}}</h1>

    <div class="col-lg-8 col-md-10 mx-auto">
         {% if object.has_image %}
         <img src="{{object.picture.url}}", width="300">
        {% endif %}

       <p class="text-right"><i>Категория</i> {{object.category}} <br>
        <i>Описание </i>{{object.description}} <br>
        <i>Сложность</i> {{object.difficulty}} <br>
      <i>Время приготовления</i> {{object.duration}} </p>

<h6>Состав на {{object.portions}} порций</h6>

          {% for item in   object.display_sostav %}

        <li> {{item}} </li>

        {% endfor %}



<h6>Технология приготовления</h6>

                        <p>

                            {{object.text}}
                        </p>


    </div>
    <p>Автор рецепта {{object.author}} </p>
    <a href="{% url 'cookbook:recipe_update' pk=object.pk %}">
            Редактировать рецепт
        </a>
</div>
{% endblock %}

cookbook/bookapp/templates/bookapp/simple.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Empty</title>
</head>
<body>
    <button type="button" id="categories">Категории</button>
    <button type="button" id="posts">Рецепты</button>
    <button type="button" id="all">Все</button>

    <ul id="div_categories"></ul>
    <hr>
    <ol id="div_posts"></ol>

<script src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/my1.js' %}"></script>

</body>
</html>